### ISSUE TITLE
Possible bug while using with complex type objects?

### ISSUE THREAD

**Issue by poikilotherm** [f-lopes/spring-mvc-test-utils#3]
Dear @f-lopes,

I just posted a question at StackOverflow, while experiencing a tricky bug in my tests.
https://stackoverflow.com/q/49782283/9457141

Maybe you have a clue if this could be related to using your little helper and hitting some hidden bug?

Your help would be very much appreciated!

Cheers
Oliver

**Comment by poikilotherm** [comment]
Actually I think this is indeed related to using your helper... :smile: 

While comparing the `HTTPServletRequest` parameters, I notice the following difference:

POST parameters created by your helper
```
attributes[0]: RQASJc
attributes[1]: ryADf9
defaults: {RQASJc=, ryADf9=}
displayName: svVWw7AUjE
mandatory: {RQASJc=true, ryADf9=true}
multiDoc: true
name: LhzsGo
system: false
```

POST parameters created by Thymeleaf/Spring combination:
```
attributes[0]: RQASJc
attributes[1]: ryADf9
defaults[RQASJc]:
defaults[ryADf9]:
displayName: svVWw7AUjE
mandatory[RQASJc]: true
_mandatory[RQASJc]: on
mandatory[ryADf9]: true
_mandatory[ryADf9]: on
multiDoc: true
name: LhzsGo
system: false
```

When there are optional attributes, the `mandatory[name]` parameter is missing, but the `_mandatory[name]: on` is still present, which result in a null entry within the map (which is alright, because I check for this in my validator, etc).

Is this handled differently in JSP than Thymeleaf?

**Comment by f-lopes** [comment]
Dear @poikilotherm, 

Thanks for your feedback.

The tool's goal is to create corresponding HTTP request parameters for a given object using reflection to collect the form fields. I have cloned the repository you mentioned in the StackOverflow issue and the given DTO doesn't declare a "_mandatory" field, hence the tool cannot generate the corresponding HTTP request parameters.

As you suggest, the issue is maybe related to the way the controller binds these request parameters to the form object. Adding "_mandatory" field makes the test pass.

For your information, the next version will support the default property editors registered with Spring MVC.

**Comment by poikilotherm** [comment]
Dear @f-lopes,

I am not sure I got you correct...
> Adding _mandatory HTTP request parameter makes the test pass

Did you just do something like
```
ResultActions result = mvc.perform(postForm("/admin/doctypes/edit/"+this.valid.getName(), this.valid)
                                                        .param("_mandatory[name]", on)
                                                        );
```
to make the tests pass?

Because when I use 
```
ResultActions result = mvc.perform(post("/admin/doctypes/edit/{name}", this.valid.getName())
                                         .param("name", this.valid.getName())
                                         .param("displayName", this.valid.getDisplayName())
                                         .param("system", this.valid.getSystem().toString())
                                         .param("multiDoc", this.valid.getMultiDoc().toString())
                                         .param("attributes[0]", this.valid.getAttributes().get(0))
                                         .param("attributes[1]", this.valid.getAttributes().get(1))
                                         .param("mandatory["+this.valid.getAttributes().get(0)+"]", this.valid.getMandatory().get(this.valid.getAttributes().get(0)).toString())
                                         .param("mandatory["+this.valid.getAttributes().get(1)+"]", this.valid.getMandatory().get(this.valid.getAttributes().get(1)).toString())
                                         .param("defaults["+this.valid.getAttributes().get(0)+"]", this.valid.getDefaults().get(this.valid.getAttributes().get(0)))
                                         .param("defaults["+this.valid.getAttributes().get(1)+"]", this.valid.getDefaults().get(this.valid.getAttributes().get(1)))
    );
```
and thus have no `_mandatory[...]` inside, the tests start passing, too (as I wrote above, the `_mandatory[...]` is [added by Thymeleaf for being on the safe side](https://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html#checkbox-fields)).

The main difference IMHO seems to be the representation of the `Map` - my above code uses the representation mentioned in the (Spring docs about conventions)[https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-beans-conventions].

Could you paste the changed code you came up with here?

**Comment by f-lopes** [comment]
Dear @poikilotherm,

I just added a `_mandatory` field at runtime to the HTTP request parameters before submitting the form.

The support for Map may need some rework and I will integrate it into the next release (work in progress). As you pointed out in https://github.com/f-lopes/spring-mvc-test-utils/issues/3#issuecomment-380816376, the Map entries need to be handled as an array.

**Comment by poikilotherm** [comment]
I am willing to contribute if you are interested. Just let me know...

**Comment by f-lopes** [comment]
Thanks for your help, I just committed a fix for this issue: https://github.com/f-lopes/spring-mvc-test-utils/commit/85225defd9e7de972352cdfeecdf096f9b4612c9
This commit just add support for simple Map (<String, String>). Don't hesitate to create a pull request if you want to enhance the Map support.

**Comment by poikilotherm** [comment]
Your extension works great!

It also works pretty well for other simple object types like Boolean, etc.

**Comment by f-lopes** [comment]
Thanks for your feedback!

> Should the README state some lines about the limitations/restrictions on usable and supported data types?

I think you're right, I will see how I can integrate it into the README.

I plan to release a new version this week: 
- Will add support for a lot of complex types: the tool will rely on Spring's default property editors.
- I will also rework the conversion process: the strategy is to always give the user the possibility to override this by providing a custom property editor (in case of a bug).
